### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mxrshall** [mxrshall/E-Travel#1]
- [x] Vytvoriť folder pre univerzálne komponenty **30.3**
- [x] Vytvoriť univerzálny komponent pre Title a Description **30.3**
- [x] Vytvoriť univerzálny button komponent **30.3**
- [x] Prerobiť Vyhladavanie **1.4**
- [x] Skusiť prerobiť slider
- [x] Doplniť texty a obrazky **31.3**
- [x] Obrazky v rovnakom rozliseni a .webp **31.3**
- [x] Pridanie tagov **31.3**
- [x] Prerobiť Onas podstranku **1.4**
- [x] Odstranenie scroll baru **31.3**
- [x] Overlay obrazkov pri lokacii podstranke
- [x] Vytvoriť prechod medzi stránkami
- [x] Galeria bude mať nahodne poradie obrazkov **7.4**
